### ISSUE TITLE
LDAP4Net?

### ISSUE THREAD

**Issue by JustinGrote** [SCRT-HQ/ActiveDirectoryCore#19]
Just curious why the Novell cross compiled library was used instead of something more modern like ldap4net (if there were any decisions around that)
https://github.com/flamencist/ldap4net

**Comment by IISResetMe** [comment]
We discussed it briefly back in March and went with Novell's lib because it's tested and stable whereas `ldap4net` (at the time at least) looked more like a work in progress - and @indented-automation had already written some code against the Novell implementation, simple as that :)
